### ISSUE TITLE
Dramatically cut down CI build time by only installing missing dependencies

### ISSUE THREAD

**Issue by stefanv** [resampling-stats/resampling-with#116]
We cache R dependencies, so no need to re-install them every time.

See, e.g., https://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them for workarounds.

**Comment by matthew-brett** [comment]
From that link - I wonder whether we should consider [packrat](https://rstudio.github.io/packrat/) or [renv](https://rstudio.github.io/renv/articles/renv.html).  Not sure what the implications are for caching there.

**Comment by stefanv** [comment]
Packrat seems to be dead, at least judging from the mailing list discussions.

**Comment by stefanv** [comment]
Seems like caching works.
