### ISSUE TITLE
Line missing in python ambulances example

### ISSUE THREAD

**Issue by iusgit** [resampling-stats/resampling-with#143]
Hi,

just tested the ambulance.ipynb notebook and got an error, because the variable `rnd` is not defined. The line 
```
rnd = np.random.default_rng()
``` 
is missing.

See https://github.com/resampling-stats/resampling-with/blob/1adf56fce57603e38661c5131ae9da777e6ced1e/source/resampling_method.Rmd#L620

**Comment by matthew-brett** [comment]
It works for me - `rnd` is defined at https://github.com/resampling-stats/resampling-with/blob/1adf56fce57603e38661c5131ae9da777e6ced1e/source/resampling_method.Rmd#L286 - is it possible you ran the cells out of order?

**Comment by iusgit** [comment]
Yes, but it is said (https://github.com/resampling-stats/resampling-with/blob/1adf56fce57603e38661c5131ae9da777e6ced1e/source/resampling_method.Rmd#L615C30-L616C14): "Here is the whole solution to the problem, without
the comments:".

In my opinion it should run without prior commands...

**Comment by matthew-brett** [comment]
Yes, that's fair enough - we do import Numpy there as well.  I've changed that in commit 795b125
