### ISSUE TITLE
Callout boxes with LaTeX?

### ISSUE THREAD

**Issue by matthew-brett** [resampling-stats/resampling-with#30]
How should our new callout boxes work with LaTeX?  At the moment they don't, and I had to fudge it with https://github.com/matthew-brett/resampling-with/commit/244a55370c2dee138222d82626bd0e8610e2dde8

What should the LaTeX equivalent be?  Should we be using [block2](https://bookdown.org/yihui/bookdown/custom-blocks.html) instead?  Or can we handle this by continuing with these [Pandoc div blocks](https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html).

**Comment by stefanv** [comment]
Resolved by adding a matching LaTeX environment.
