### ISSUE TITLE
All web pages should be Makefile requirements for web build

### ISSUE THREAD

**Issue by matthew-brett** [resampling-stats/resampling-with#84]
See `source/Makefile` e.g.

```
python-html-book: ../python-book/index.html
```

but should be:

```
python-html-book: $(html_ouputs)
```

**Comment by stefanv** [comment]
This is the obvious correct way to do it, but until quarto supports parallel builds, we may have to *not* declare the dependency.

**Comment by stefanv** [comment]
xref: https://github.com/quarto-dev/quarto-cli/issues/6116

**Comment by matthew-brett** [comment]
@stefanv - we can close this can't we - Ninja takes care of the build dependencies, does it not?
