### ISSUE TITLE
Do doc build on PRs

### ISSUE THREAD

**Issue by matthew-brett** [resampling-stats/resampling-with#94]
Y'all know what I mean ...

**Comment by stefanv** [comment]
The book builds are already happening, but the resulting draft website is not being reported. See https://github.com/resampling-stats/resampling-with/pull/115

With "doc" you mean "book", or something else?

**Comment by matthew-brett** [comment]
Yes, right - I just meant the book builds.  Does the CircleCI solution fix the problem?

**Comment by stefanv** [comment]
Closed by #115
